"""Reusable column groups for ORM models."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, declared_attr, mapped_column


class UUIDPrimaryKeyMixin:
    """A UUID primary key generated by the application.

    Generated in Python rather than by the database so that the id is known
    before the INSERT, which keeps related objects easy to build in one unit of
    work and avoids depending on a server-side extension.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class CreatedAtMixin:
    """Creation timestamp, for rows that are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class TimestampMixin:
    """Creation and update timestamps, both maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class OrganizationScopedMixin:
    """Marks a table as owned by one tenant.

    Declaring the column once is what makes tenant scoping auditable: every
    table carrying this mixin has a non-null, indexed ``organization_id``, so
    the scoped repositories - and the row-level security policies that will
    back them - have a single predicate to apply everywhere.

    ``ON DELETE CASCADE`` means removing an organization removes its data. In
    normal operation an organization is archived via its status rather than
    deleted; the cascade exists so that a genuine tenant off-boarding is one
    statement instead of fifteen.

    A ``declared_attr`` is required because a ``ForeignKey`` column object
    cannot be shared between mapped classes.
    """

    @declared_attr
    @classmethod
    def organization_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            PgUUID(as_uuid=True),
            ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
