"""Schema definition: what the models declare, checked without a database.

These assert the shape Alembic will emit - types, keys, constraints, indexes and
tenant columns - so a mistake is caught at the model, not after a migration has
been applied somewhere.
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import Boolean, DateTime, Integer, String, Table, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import configure_mappers

from app.models import (
    Agent,
    AgentTool,
    Approval,
    AuditEvent,
    Base,
    Conversation,
    Document,
    Message,
    Organization,
    OrganizationMember,
    Tool,
    User,
    Workflow,
    WorkflowRun,
    WorkflowStep,
    WorkflowStepRun,
)
from app.models.enums import (
    ApprovalStatus,
    ConversationStatus,
    DocumentStatus,
    MemberRole,
    MembershipStatus,
    MessageRole,
    OrganizationStatus,
    RunStatus,
    StepRunStatus,
    UserStatus,
    WorkflowStepType,
)

ALL_MODELS = [
    Agent,
    AgentTool,
    Approval,
    AuditEvent,
    Conversation,
    Document,
    Message,
    Organization,
    OrganizationMember,
    Tool,
    User,
    Workflow,
    WorkflowRun,
    WorkflowStep,
    WorkflowStepRun,
]

EXPECTED_TABLES = {
    "agent_tools",
    "agents",
    "approvals",
    "audit_events",
    "conversations",
    "documents",
    "messages",
    "organization_members",
    "organizations",
    "tools",
    "users",
    "workflow_runs",
    "workflow_step_runs",
    "workflow_steps",
    "workflows",
}

# Tables that carry the tenant discriminator directly.
TENANT_SCOPED = {
    "agents",
    "approvals",
    "audit_events",
    "conversations",
    "documents",
    "organization_members",
    "workflow_runs",
    "workflows",
}

# Tables without organization_id, and why that is correct.
NOT_TENANT_SCOPED = {
    "organizations": "is the tenant",
    "users": "global; membership carries the tenant",
    "tools": "platform-level registry",
    "agent_tools": "reaches its tenant through the agent",
    "messages": "reaches its tenant through the conversation",
    "workflow_steps": "reaches its tenant through the workflow",
    "workflow_step_runs": "reaches its tenant through the run",
}


def table_of(model: type) -> Table:
    return model.__table__  # type: ignore[attr-defined, no-any-return]


# -- Imports and registration -------------------------------------------------


def test_all_models_import() -> None:
    """Every model is importable from the package root."""
    assert len(ALL_MODELS) == 15
    for model in ALL_MODELS:
        assert issubclass(model, Base)


def test_mappers_configure() -> None:
    """A bad relationship raises here rather than on the first query."""
    configure_mappers()


def test_metadata_contains_exactly_the_expected_tables() -> None:
    """Alembic emits Base.metadata, so a missing import means a missing table."""
    assert set(Base.metadata.tables) == EXPECTED_TABLES


def test_every_model_is_registered_in_metadata() -> None:
    registered = {table_of(model).name for model in ALL_MODELS}
    assert registered == EXPECTED_TABLES


# -- Primary keys -------------------------------------------------------------


@pytest.mark.parametrize("model", [m for m in ALL_MODELS if m is not AgentTool])
def test_uuid_primary_key(model: type) -> None:
    table = table_of(model)
    primary_key = list(table.primary_key.columns)

    assert len(primary_key) == 1, f"{table.name} should have a single-column key"
    column = primary_key[0]
    assert column.name == "id"
    assert isinstance(column.type, PgUUID)
    assert column.default is not None, "id must be generated by the application"


def test_agent_tools_uses_a_composite_primary_key() -> None:
    """The join table is keyed by the pair, which makes a duplicate grant
    impossible without a separate unique constraint."""
    table = table_of(AgentTool)
    names = [column.name for column in table.primary_key.columns]

    assert names == ["agent_id", "tool_id"]
    for column in table.primary_key.columns:
        assert isinstance(column.type, PgUUID)


def test_primary_key_default_produces_uuids() -> None:
    generated = table_of(Organization).c.id.default.arg(None)  # type: ignore[union-attr]
    assert isinstance(generated, uuid.UUID)


# -- Tenant scoping -----------------------------------------------------------


@pytest.mark.parametrize("table_name", sorted(TENANT_SCOPED))
def test_tenant_tables_have_a_non_null_indexed_organization_id(table_name: str) -> None:
    table = Base.metadata.tables[table_name]

    assert "organization_id" in table.c, f"{table_name} must carry the tenant id"
    column = table.c.organization_id
    assert isinstance(column.type, PgUUID)
    assert column.nullable is False, "a tenant-owned row must always have an owner"

    targets = {fk.column.table.name for fk in column.foreign_keys}
    assert targets == {"organizations"}

    indexed = any(next(iter(index.columns)).name == "organization_id" for index in table.indexes)
    assert indexed, f"{table_name}.organization_id must lead an index"


@pytest.mark.parametrize("table_name", sorted(NOT_TENANT_SCOPED))
def test_non_tenant_tables_have_no_organization_id(table_name: str) -> None:
    """Documented on purpose: duplicating the column would create a second
    source of truth that could disagree with the first."""
    assert "organization_id" not in Base.metadata.tables[table_name].c


def test_tenant_scoping_covers_every_table() -> None:
    assert TENANT_SCOPED | set(NOT_TENANT_SCOPED) == EXPECTED_TABLES


def test_organization_cascade_removes_tenant_data() -> None:
    for table_name in TENANT_SCOPED:
        column = Base.metadata.tables[table_name].c.organization_id
        fk = next(iter(column.foreign_keys))
        assert fk.ondelete == "CASCADE", table_name


# -- Timestamps ---------------------------------------------------------------


def test_every_table_has_a_timezone_aware_created_at() -> None:
    for name, table in Base.metadata.tables.items():
        assert "created_at" in table.c, name
        column = table.c.created_at
        assert isinstance(column.type, DateTime)
        assert column.type.timezone is True, f"{name}.created_at must be timezone-aware"
        assert column.server_default is not None


def test_mutable_tables_have_updated_at_and_append_only_ones_do_not() -> None:
    append_only = {"messages", "audit_events", "agent_tools"}

    for name, table in Base.metadata.tables.items():
        if name in append_only:
            assert "updated_at" not in table.c, f"{name} is append-only"
        else:
            assert "updated_at" in table.c, name
            assert table.c.updated_at.type.timezone is True


def test_all_timestamp_columns_are_timezone_aware() -> None:
    for name, table in Base.metadata.tables.items():
        for column in table.c:
            if isinstance(column.type, DateTime):
                assert column.type.timezone is True, f"{name}.{column.name}"


# -- JSONB --------------------------------------------------------------------


@pytest.mark.parametrize(
    ("model", "column_name", "nullable"),
    [
        (WorkflowStep, "configuration", False),
        (WorkflowStepRun, "input_data", True),
        (WorkflowStepRun, "output_data", True),
        (Approval, "parameters", False),
        (AuditEvent, "metadata", False),
    ],
)
def test_jsonb_columns(model: type, column_name: str, nullable: bool) -> None:
    column = table_of(model).c[column_name]

    assert isinstance(column.type, JSONB)
    assert column.nullable is nullable


def test_audit_metadata_column_is_named_metadata_but_mapped_elsewhere() -> None:
    """``metadata`` is reserved on a declarative class - it is the MetaData
    object - so the attribute is renamed while the column keeps the name."""
    assert "metadata" in table_of(AuditEvent).c
    assert AuditEvent.event_metadata.key == "event_metadata"
    assert AuditEvent.__table__.c.metadata.name == "metadata"


def test_non_null_jsonb_columns_default_to_an_empty_object() -> None:
    for model, column_name in ((WorkflowStep, "configuration"), (Approval, "parameters")):
        column = table_of(model).c[column_name]
        assert column.default is not None
        assert column.server_default is not None


# -- Enums --------------------------------------------------------------------


@pytest.mark.parametrize(
    ("model", "column_name", "enum_class"),
    [
        (Organization, "status", OrganizationStatus),
        (User, "status", UserStatus),
        (OrganizationMember, "role", MemberRole),
        (OrganizationMember, "status", MembershipStatus),
        (Conversation, "status", ConversationStatus),
        (Message, "role", MessageRole),
        (Document, "status", DocumentStatus),
        (WorkflowStep, "step_type", WorkflowStepType),
        (WorkflowRun, "status", RunStatus),
        (WorkflowStepRun, "status", StepRunStatus),
        (Approval, "status", ApprovalStatus),
    ],
)
def test_enum_columns_store_values_and_are_constrained(
    model: type, column_name: str, enum_class: type
) -> None:
    column = table_of(model).c[column_name]

    assert column.nullable is False
    # Stored as VARCHAR + CHECK, so a value can be added without a type change.
    assert column.type.native_enum is False  # type: ignore[attr-defined]
    assert column.type.create_constraint is True  # type: ignore[attr-defined]
    # The lowercase values, not the member names.
    assert set(column.type.enums) == {  # type: ignore[attr-defined]
        str(member.value)
        for member in enum_class  # type: ignore[attr-defined]
    }


def test_member_roles_are_owner_admin_member() -> None:
    assert [role.value for role in MemberRole] == ["owner", "admin", "member"]


def test_message_roles_match_the_model_api() -> None:
    assert {role.value for role in MessageRole} == {"user", "assistant", "system", "tool"}


def test_workflow_step_types() -> None:
    assert {t.value for t in WorkflowStepType} == {
        "tool_call",
        "agent_step",
        "approval",
        "condition",
    }


# -- Unique constraints -------------------------------------------------------


def unique_column_sets(model: type) -> set[frozenset[str]]:
    table = table_of(model)
    from sqlalchemy import UniqueConstraint

    sets = {
        frozenset(column.name for column in constraint.columns)
        for constraint in table.constraints
        if isinstance(constraint, UniqueConstraint)
    }
    sets |= {
        frozenset(column.name for column in index.columns)
        for index in table.indexes
        if index.unique
    }
    return sets


def test_organization_slug_is_unique() -> None:
    assert frozenset({"slug"}) in unique_column_sets(Organization)


def test_user_email_is_unique() -> None:
    assert frozenset({"email"}) in unique_column_sets(User)


def test_tool_name_is_globally_unique() -> None:
    assert frozenset({"name"}) in unique_column_sets(Tool)


def test_document_storage_key_is_unique() -> None:
    assert frozenset({"storage_key"}) in unique_column_sets(Document)


def test_a_user_holds_one_membership_per_organization() -> None:
    assert frozenset({"organization_id", "user_id"}) in unique_column_sets(OrganizationMember)


def test_names_are_unique_within_an_organization_not_across_them() -> None:
    for model in (Agent, Workflow):
        assert frozenset({"organization_id", "name"}) in unique_column_sets(model)
        assert frozenset({"name"}) not in unique_column_sets(model)


def test_workflow_step_order_is_unique_within_a_workflow() -> None:
    assert frozenset({"workflow_id", "step_order"}) in unique_column_sets(WorkflowStep)


# -- Foreign keys -------------------------------------------------------------


@pytest.mark.parametrize(
    ("model", "column_name", "target", "ondelete"),
    [
        (OrganizationMember, "user_id", "users", "CASCADE"),
        (OrganizationMember, "organization_id", "organizations", "CASCADE"),
        (AgentTool, "agent_id", "agents", "CASCADE"),
        (AgentTool, "tool_id", "tools", "CASCADE"),
        (Conversation, "agent_id", "agents", "CASCADE"),
        # A person leaving must not erase what was asked and done.
        (Conversation, "user_id", "users", "RESTRICT"),
        (Message, "conversation_id", "conversations", "CASCADE"),
        # The document outlives the account that uploaded it.
        (Document, "uploaded_by", "users", "SET NULL"),
        (WorkflowStep, "workflow_id", "workflows", "CASCADE"),
        (WorkflowRun, "workflow_id", "workflows", "CASCADE"),
        (WorkflowStepRun, "workflow_run_id", "workflow_runs", "CASCADE"),
        (WorkflowStepRun, "workflow_step_id", "workflow_steps", "CASCADE"),
        (Approval, "requested_by", "users", "RESTRICT"),
        (Approval, "approved_by", "users", "SET NULL"),
        (Approval, "tool_id", "tools", "RESTRICT"),
        # The trail survives the account it refers to.
        (AuditEvent, "user_id", "users", "SET NULL"),
    ],
)
def test_foreign_key_targets_and_delete_behaviour(
    model: type, column_name: str, target: str, ondelete: str
) -> None:
    column = table_of(model).c[column_name]
    foreign_key = next(iter(column.foreign_keys))

    assert foreign_key.column.table.name == target
    assert foreign_key.ondelete == ondelete


def test_audit_resource_reference_is_not_a_foreign_key() -> None:
    """The trail spans every table and must outlive the rows it describes."""
    column = table_of(AuditEvent).c.resource_id

    assert isinstance(column.type, PgUUID)
    assert not column.foreign_keys


def test_every_foreign_key_column_is_indexed() -> None:
    """An unindexed foreign key makes both joins and cascading deletes slow."""
    missing: list[str] = []

    for name, table in Base.metadata.tables.items():
        indexed = {next(iter(index.columns)).name for index in table.indexes}
        indexed |= {next(iter(table.primary_key.columns)).name}
        indexed |= {
            next(iter(constraint.columns)).name
            for constraint in table.constraints
            if hasattr(constraint, "columns") and list(constraint.columns)
        }
        for column in table.c:
            if column.foreign_keys and column.name not in indexed:
                missing.append(f"{name}.{column.name}")

    assert not missing, f"unindexed foreign keys: {missing}"


# -- Column types -------------------------------------------------------------


def test_key_text_columns_use_sensible_types() -> None:
    assert isinstance(table_of(User).c.email.type, String)
    assert table_of(User).c.email.type.length == 320  # RFC 5321 maximum
    assert isinstance(table_of(Agent).c.system_instructions.type, Text)
    assert isinstance(table_of(Message).c.content.type, Text)
    assert isinstance(table_of(Document).c.size_bytes.type, Integer)
    assert isinstance(table_of(Agent).c.enabled.type, Boolean)


def test_password_hash_exists_but_is_optional() -> None:
    """The authentication phase populates it; an invited user has none yet."""
    column = table_of(User).c.password_hash

    assert column.nullable is True


def test_agents_require_a_model() -> None:
    assert table_of(Agent).c.model.nullable is False


def test_tools_carry_the_approval_flag() -> None:
    column = table_of(Tool).c.requires_approval

    assert isinstance(column.type, Boolean)
    assert column.nullable is False


# -- Relationships ------------------------------------------------------------


@pytest.mark.parametrize(
    ("model", "attribute", "target"),
    [
        (Organization, "members", OrganizationMember),
        (User, "memberships", OrganizationMember),
        (OrganizationMember, "organization", Organization),
        (OrganizationMember, "user", User),
        (Agent, "tools", Tool),
        (Tool, "agents", Agent),
        (Conversation, "messages", Message),
        (Message, "conversation", Conversation),
        (Conversation, "agent", Agent),
        (Workflow, "steps", WorkflowStep),
        (WorkflowStep, "workflow", Workflow),
        (WorkflowRun, "workflow", Workflow),
        (WorkflowRun, "step_runs", WorkflowStepRun),
        (WorkflowStepRun, "workflow_run", WorkflowRun),
        (WorkflowStepRun, "step", WorkflowStep),
        (Approval, "requester", User),
        (Approval, "approver", User),
        (Approval, "agent", Agent),
        (Approval, "tool", Tool),
        (Approval, "conversation", Conversation),
        (AuditEvent, "organization", Organization),
        (AuditEvent, "user", User),
    ],
)
def test_relationship_targets(model: type, attribute: str, target: type) -> None:
    configure_mappers()
    relationship = model.__mapper__.relationships[attribute]  # type: ignore[attr-defined]

    assert relationship.mapper.class_ is target


def test_agent_tool_link_is_many_to_many_through_agent_tools() -> None:
    configure_mappers()
    relationship = Agent.__mapper__.relationships["tools"]

    assert relationship.secondary is table_of(AgentTool)


def test_messages_load_in_a_deterministic_order() -> None:
    """created_at alone is not enough: now() is constant per transaction."""
    configure_mappers()
    order_by = Conversation.__mapper__.relationships["messages"].order_by

    assert [clause.name for clause in order_by] == ["created_at", "id"]


def test_owned_children_are_deleted_with_their_parent() -> None:
    configure_mappers()
    for model, attribute in (
        (Organization, "members"),
        (Conversation, "messages"),
        (Workflow, "steps"),
        (WorkflowRun, "step_runs"),
    ):
        relationship = model.__mapper__.relationships[attribute]  # type: ignore[attr-defined]
        assert relationship.cascade.delete_orphan
        # The database performs the delete; the ORM must not load the children
        # only to delete them one by one.
        assert relationship.passive_deletes is True
