"""business operations schema

Revision ID: 3679391a4d0d
Revises: ffa31649bd78
Created: 2026-09-15 02:49:19.071298+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3679391a4d0d"
down_revision: str | None = "ffa31649bd78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status", native_enum=False, create_constraint=True),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_customers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("id", "organization_id", name="uq_customers_id_organization_id"),
        sa.UniqueConstraint(
            "organization_id", "reference", name="uq_customers_organization_reference"
        ),
    )
    op.create_index(
        op.f("ix_customers_organization_id"), "customers", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_customers_organization_id_status",
        "customers",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "shipments",
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_transit",
                "delivered",
                "cancelled",
                "exception",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("carrier", sa.String(length=100), nullable=True),
        sa.Column("origin", sa.String(length=200), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "organization_id"],
            ["customers.id", "customers.organization_id"],
            name="fk_shipments_customer_id_organization_id_customers",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_shipments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("id", "organization_id", name="uq_shipments_id_organization_id"),
        sa.UniqueConstraint(
            "organization_id", "reference", name="uq_shipments_organization_reference"
        ),
    )
    op.create_index(
        "ix_shipments_customer_id_organization_id",
        "shipments",
        ["customer_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipments_organization_id"), "shipments", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_shipments_organization_id_status",
        "shipments",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "partially_paid",
                "paid",
                "cancelled",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_invoices_invoices_currency_iso4217")
        ),
        sa.CheckConstraint(
            "amount_paid >= 0", name=op.f("ck_invoices_invoices_amount_paid_not_negative")
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_invoices_invoices_total_not_negative")),
        sa.ForeignKeyConstraint(
            ["customer_id", "organization_id"],
            ["customers.id", "customers.organization_id"],
            name="fk_invoices_customer_id_organization_id_customers",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invoices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id", "organization_id"],
            ["shipments.id", "shipments.organization_id"],
            name="fk_invoices_shipment_id_organization_id_shipments",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("organization_id", "number", name="uq_invoices_organization_number"),
    )
    op.create_index(
        "ix_invoices_customer_id_organization_id",
        "invoices",
        ["customer_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_invoices_organization_id_status",
        "invoices",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_shipment_id_organization_id",
        "invoices",
        ["shipment_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "shipment_charges",
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column(
            "charge_type",
            sa.Enum(
                "freight",
                "fuel_surcharge",
                "customs_duty",
                "handling",
                "storage",
                "insurance",
                name="charge_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "outstanding",
                "paid",
                "waived",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="outstanding",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_shipment_charges_shipment_charges_currency_iso4217"),
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_shipment_charges_shipment_charges_amount_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_shipment_charges_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id", "organization_id"],
            ["shipments.id", "shipments.organization_id"],
            name="fk_shipment_charges_shipment_id_organization_id_shipments",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_charges")),
    )
    op.create_index(
        op.f("ix_shipment_charges_organization_id"),
        "shipment_charges",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_shipment_charges_organization_id_status",
        "shipment_charges",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_shipment_charges_shipment_id_organization_id",
        "shipment_charges",
        ["shipment_id", "organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipment_charges_shipment_id_organization_id", table_name="shipment_charges")
    op.drop_index("ix_shipment_charges_organization_id_status", table_name="shipment_charges")
    op.drop_index(op.f("ix_shipment_charges_organization_id"), table_name="shipment_charges")
    op.drop_table("shipment_charges")
    op.drop_index("ix_invoices_shipment_id_organization_id", table_name="invoices")
    op.drop_index("ix_invoices_organization_id_status", table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index("ix_invoices_customer_id_organization_id", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_shipments_organization_id_status", table_name="shipments")
    op.drop_index(op.f("ix_shipments_organization_id"), table_name="shipments")
    op.drop_index("ix_shipments_customer_id_organization_id", table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_customers_organization_id_status", table_name="customers")
    op.drop_index(op.f("ix_customers_organization_id"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
